[package]
name = "pls"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.39", features = ["derive"] }
colored = "3.0.0"
console = "0.15.11"
dirs = "6.0.0"
git2 = "0.20.2"
nix = { version = "0.30.1", features = ["fs", "user"] }
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
unicode-width = "0.2.1"
