[package]
name = "pls"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.39", features = ["derive"] }
colored = "3.0.0"
getset = "0.1.5"
nix = { version = "0.30.1", features = ["fs", "user"] }
rayon = "1.10.0"
