[package]
name = "pls"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
dirs = "6.0.0"
figura = "1.0.2"
serde = { version = "1.0.219", features = ["derive"] }
smacro = "0.1.0"
strip-ansi-escapes = "0.2.1"
toml = "0.8.23"
unicode-width = "0.2.1"
